### ISSUE TITLE
Adding support for HDF5: feasible?

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab-data-explorer#31]
I'm looking into whether I can build on this extension in order to implement a long-held ambition: an HDF5 file viewer for Jlab. 

An HDF5 file is kind of like its own mini filesystem: there's a tree of groups (equivalent to directories), and each group may contain datasets and/or other groups. My basic idea would be to expose the group tree in the dataset browser, and then be able to open/view a given dataset (assuming it's 2D or less) as a grid in the main area.

Along those lines, I have a bunch of questions:
- Does this seem feasible/in line with your vision of this extension?
- What exactly would I need to add to this extension in order to support HDF5? It looks like I'd at least need to add an appropriate converter in `dataregistry-extension/src/files.tsx`. Would anything else be required?
- Does this extension have any stuff to help deal with large files?
- It seems that the text in the grid view is not selectable, which is a little bit killer. The grid is implemented via the datagrid stuff from Phosphor, right? Is this an upstream issue?

**Comment by saulshanabrook** [comment]
> Does this seem feasible/in line with your vision of this extension?

Definitely! We have talked about having a HDF5 explorer a lot and I would be happy to help with this.

> What exactly would I need to add to this extension in order to support HDF5? 

You would have to define a couple of different converters. I am in the process of adding support for viewing notebook outputs in the data registry, which will give you another converter to look at. 

In a rough overview, I think you would have to add:

1. A converter to recognize that certain files are HDF5 files, probably based on their file ending?
2. A converter to show the nested datasets inside of a HDF5 file. I guess these would be the groups and datasets?  This would be similar to the existing [folder converter](https://github.com/jupyterlab/jupyterlab-data-explorer/blob/febd6ad6bbe20254530da6f4d8bc64c20d54ae8b/dataregistry/src/folders.ts#L40-L46). Each sub datasets would have to get it's own IRI. For notebooks, I created ones like `file:///notebook.ipynb#/cells/0/output/0`. You would have to invent something similar to point to the group/dataset inside of the file.
3. A converter to actually view the datasets inside an HDF5 file in some way. This could use the data grid extension or any other JS table widget.

Steps 2 and 3 would likely need to use a corresponding server extension. Otherwise, you would have to load in the whole HDF5 file into memory in the browser and parse it there, which would not be ideal.

> Does this extension have any stuff to help deal with large files?

Not currently! There is nothing stopping from plugging this functionality in, but like I said above it would probably involve a server extension.

> It seems that the text in the grid view is not selectable, which is a little bit killer. The grid is implemented via the datagrid stuff from Phosphor, right? Is this an upstream issue?

Yes I believe so. We have support for the Phosphor datagrid, but it is no way the only supported view option. We can just as easily support any other JS library to visualize data.

**Comment by telamonian** [comment]
> We have talked about having a HDF5 explorer a lot

I have seen a number of abortive attempts at this (including [my own](https://github.com/telamonian/jupyterlab-hdf5)). One of the missing pieces was always a filebrowser-like widget for navigating the group tree, so the datasets browser in this package should be a big help towards actually making an HDF5 browser happen.

I think the minimum viable product here will just be a functional HDF5 browser, so the large file stuff can wait until later. I'm hoping it won't be too complicated to at least limit the downloaded data to the metadata and the contents of the currently open datasets. Separately, it looks like @ian-r-rose was making some progress on large HDF5 files over at [ian-r-rose/jupyterlab-remote-data](https://github.com/ian-r-rose/jupyterlab-remote-data). Maybe that can be folded into this repo at some point.

I'll start looking into implementing 1., 2., and 3. A few things off the top of my head: 
- The HDF5 apis already support paths of the form `group/subgroup/foodata`, so the IRI's should be easy to set up.
- The `h5py` Python package is an order of magnitude more elegant and easy to use than any other HDF5 api, so I think a server extension is a good idea in any case.
- Do you have any recommendations for good alternative JS table widgets?

**Comment by saulshanabrook** [comment]
> One of the missing pieces was always a filebrowser-like widget for navigating the group tree, so the datasets browser in this package should be a big help towards actually making an HDF5 browser happen.

Yeah then I think this is a great fit. Right now the UX is pretty proof-of-concept quality but we plan on putting some cycles into improving it.

> The h5py Python package is an order of magnitude more elegant and easy to use than any other HDF5 api, so I think a server extension is a good idea in any case.

Great, well I think wrapping that in a web server and using that as a server extension would make sense then.

> Do you have any recommendations for good alternative JS table widgets?

There are a few I have seen used for alternative JL implementations:

* https://github.com/finos/perspective
* https://github.com/quantopian/qgrid

**Comment by saulshanabrook** [comment]
Closing this since now @telamonian has released a hdf plugin with dataregistry support https://github.com/telamonian/jupyterlab-hdf/blob/master/src/dataregistry.ts
