### ISSUE TITLE
Data Browser not expanding downward in window

### ISSUE THREAD

**Issue by kylemcmearty** [jupyterlab/jupyterlab-data-explorer#94]
I downloaded data-explorer from Ubuntu terminal and Jupyterlab extension manager. When I open the grid view for my .csv dataset, I can only view 2 records at a time. It appears the Data-Browser window is not fully expanding downward. 

![Screenshot from 2019-09-25 23-27-06](https://user-images.githubusercontent.com/10493854/65656250-3458f880-dfed-11e9-96a4-7d1a4d603256.png)

**Comment by saulshanabrook** [comment]
Hey @kmcmearty thanks for reporting this. Yeah this is a known bug currently (https://github.com/jupyterlab/jupyterlab-data-explorer/issues/53). The issue is that the phosphor datagrid needs to be be sized properly. I was actually just [asking about this on gitter](https://gitter.im/phosphorjs/phosphor?at=5d8befb7a8c2c26e9f9eaa2c). Chris suggested we try:

> set `postion: relative` of the React component. Then use `postion: absolute, left: 0, top: 0, right: 0, bottom: 0` on the DataGrid widget

Datagrid widget: https://github.com/jupyterlab/jupyterlab-data-explorer/blob/master/dataregistry-extension/src/csvviewer.ts#L28

Wrapping phosphor widget in react component: https://github.com/jupyterlab/jupyterlab-data-explorer/blob/f7ba324f7a688ccd474c028e26291644cf1101df/dataregistry-extension/src/utils.tsx#L60-L69

**Comment by saulshanabrook** [comment]
As a workaround, if you navigate to the CSV file in the left hand side data explorer pane, you should be able to click the grid button and get it full screen.

**Comment by kylemcmearty** [comment]
I navigated to the folder with my data in the left hand side data explorer pane under `file:///`. I see where it says Grid and Snippet highlighted in blue. When I click 'Grid' it doesnt do anything. 'Snippet' adds this in my cell 

```
import pandas as pd

df = pd.read_csv("Data.csv")
df

```

**Comment by saulshanabrook** [comment]
@kmcmearty Could you open your browser console and see if there are any errors there? Are you running in windows?

**Comment by kylemcmearty** [comment]
Ubuntu 18.04 LTS running JupyterLab 1.0.2 on Conda 4.7.12 in Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

![Screenshot from 2019-09-26 18-41-40](https://user-images.githubusercontent.com/10493854/65729877-d7f9e580-e08d-11e9-948b-7f7ff1d560ec.png)

Console is telling me: "Download the React DevTools for a better development experience: https://fb.me/react-devtools"    - @saulshanabrook Maybe source of issue?
